version: '3.8'

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb:/var/lib/mysql/
    env_file:
      - .env
    networks:
      - inception
    restart: always
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    volumes:
      - wordpress:/var/www/html/
    depends_on:
      - mariadb
    env_file:
      - .env
    networks:
      - inception
    restart: always
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - 443:443
      - 8080:8080
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html/
      - /home/yel-mass/data/adminer:/var/www2/html/
    env_file:
      - .env
    networks:
      - inception
    restart: always
  # Bonus part
  ftp-server:
    container_name: ftp-server
    build: ./requirements/bonus/ftp-server/
    env_file: .env
    volumes:
      - wordpress:/home/bca
    networks:
      - inception
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    restart: always
  portainer:
    container_name: portainer
    build: ./requirements/bonus/portainer/
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    depends_on:
      - wordpress
    networks:
      - inception
    ports:
      - "9443:9443"
    restart: always
  adminer:
    container_name: adminer
    build: ./requirements/bonus/adminer
    volumes:
      - /home/yel-mass/data/adminer:/var/www2/html/
    depends_on:
      - mariadb
    networks:
      - inception
    restart: always

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/yel-mass/data/mariadb/
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/yel-mass/data/wordpress/

networks:
  inception:
    name: inception



























# TODO: read more about network in docker-compose. one network

# TODO: create a volume to store the data of the mariadb.
# TODO: Read about the docker-compose and how it works.
# TODO: Read about network in docker-compose.
# TODO: Why we need docker-compose.
# TODO: Start the bonus part. (Adminer and then FTP server and then radis cache and then some useful service of your choice and then create a static web site showing your resume)

# TODO: Read about FastCGI.

# TODO: SSL certificate for nginx.
# TODO: create an .env file for the docker-compose.

# TODO: Khtaser depandicies of each container.