CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER IF NOT EXISTS 'yel-mass'@'%' IDENTIFIED BY '12345';
GRANT ALL PRIVILEGES ON wordpress.* TO 'yel-mass'@'%';
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY 'root12345';