FROM nginx:latest
COPY static-html-directory /usr/share/nginx/html

#EXPOSE 80


# To build the Docker image, use the docker build command: docker build -t name .
#                                                          -t name:tag --> tag is optional